version: "3.9"
services:
  postgres:
    container_name: postgres_recorrido
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qUhJtiDAEz"
      POSTGRES_DB: "recorrido_db"
    networks:
      - recorrido_network
  postgres_test:
    container_name: postgres_recorrido_test
    image: postgres:13
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qUhJtiDAEz"
      POSTGRES_DB: "recorrido_db_test"
    command: -p 5433
    networks:
      - recorrido_network
  web:
    container_name: rails_recorrido
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    networks:
      - recorrido_network
    stdin_open: true
    tty: true
    depends_on:
      - postgres

networks:
  recorrido_network:
  recorrido_network_test:
